"""Pygent's application-facing API.

Runtime, deployment, persistence, and provider extension contracts live in
their owning subpackages and are intentionally unavailable from this module.
"""

from __future__ import annotations

from .agent import (
    InjectionKind,
    PygentAgent,
    PygentAgentContext,
    ReActBudgetExceeded,
    ReActLayer,
    Reminder,
)
from .core import (
    Agent,
    AIMessage,
    Context,
    FrozenJsonObject,
    JsonValueError,
    Message,
    ModelContinuation,
    Module,
    RecurrentModule,
    ToolMessage,
    UserMessage,
    freeze_json,
    freeze_json_object,
    thaw_json,
)
from .llm import (
    BuiltinModelProtocol,
    CapabilityPreset,
    CapabilityPresetCatalog,
    ConnectionConfig,
    CredentialRef,
    EnabledModelConfig,
    ExponentialBackoff,
    GenerationConfig,
    ModelCallError,
    ModelCallLayer,
    ModelCallOptions,
    ModelCallPolicy,
    ModelCapabilities,
    ModelCapabilityCatalog,
    ModelConfig,
    ModelEntry,
    ModelErrorKind,
    ModelGroup,
    ModelGroupConfig,
    ModelSpec,
    ProviderCatalog,
    ProviderPreset,
    ProviderProtocolPreset,
    ResolvedModelConnection,
    RetryPolicy,
)
from .runtime.context_codec import ContextCodec
from .tool import (
    IdempotencyPolicy,
    MediaSource,
    ToolAuthorizationDecision,
    ToolAuthorizationRequest,
    ToolCall,
    ToolCallLayer,
    ToolDefinition,
    ToolKit,
    ToolOutput,
    ToolResult,
    ToolResultContent,
    ToolResultJson,
    ToolResultMedia,
    ToolResultText,
    ToolSideEffect,
    ToolSpec,
    tool,
)

__all__ = [
    "AIMessage",
    "Agent",
    "BuiltinModelProtocol",
    "CapabilityPreset",
    "CapabilityPresetCatalog",
    "ConnectionConfig",
    "Context",
    "ContextCodec",
    "CredentialRef",
    "EnabledModelConfig",
    "ExponentialBackoff",
    "FrozenJsonObject",
    "GenerationConfig",
    "IdempotencyPolicy",
    "InjectionKind",
    "JsonValueError",
    "MediaSource",
    "Message",
    "ModelCallError",
    "ModelCallLayer",
    "ModelCallOptions",
    "ModelCallPolicy",
    "ModelCapabilities",
    "ModelCapabilityCatalog",
    "ModelConfig",
    "ModelContinuation",
    "ModelEntry",
    "ModelErrorKind",
    "ModelGroup",
    "ModelGroupConfig",
    "ModelSpec",
    "Module",
    "ProviderCatalog",
    "ProviderPreset",
    "ProviderProtocolPreset",
    "PygentAgent",
    "PygentAgentContext",
    "ReActBudgetExceeded",
    "ReActLayer",
    "RecurrentModule",
    "Reminder",
    "ResolvedModelConnection",
    "RetryPolicy",
    "ToolAuthorizationDecision",
    "ToolAuthorizationRequest",
    "ToolCall",
    "ToolCallLayer",
    "ToolDefinition",
    "ToolKit",
    "ToolMessage",
    "ToolOutput",
    "ToolResult",
    "ToolResultContent",
    "ToolResultJson",
    "ToolResultMedia",
    "ToolResultText",
    "ToolSideEffect",
    "ToolSpec",
    "UserMessage",
    "freeze_json",
    "freeze_json_object",
    "thaw_json",
    "tool",
]


def __dir__() -> list[str]:
    return sorted(__all__)
