from collections.abc import Mapping

class NativeSseStream:
    def __aiter__(self) -> NativeSseStream: ...
    async def __anext__(self) -> tuple[str, str | int]: ...
    def close(self) -> None: ...
    async def wait_closed(self) -> None: ...

class NativeHttpClient:
    def __init__(
        self,
        headers: Mapping[str, str],
        trust_environment: bool,
        max_connections: int,
    ) -> None: ...
    async def request_json(
        self,
        method: str,
        url: str,
        body: str | None,
        timeout: float | None,
    ) -> tuple[int, str]: ...
    def stream_sse(self, url: str, body: str) -> NativeSseStream: ...
    async def close(self) -> None: ...
    def _limits(self) -> tuple[int, int]: ...
